<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="35.03s"
		durationms="35030"
		type="root"
		rid="2c59dc740a24a67"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Fahad Shah"
		rxversion="8.0.0.0"
		host="SM-J110H (Unknown)
WLAN - 192.168.3.169"
		osversion="-"
		runtimeversion="-"
		procarch="-"
		oslanguage="-"
		dtnlanguage="-"
		screenresolution="-"
		timestamp="4/23/2018 6:15:21 PM"
		timestampiso="2018-04-24T01:15:21"
		endtime="4/23/2018 6:15:56 PM"
		timeoutfactor="1"
		module="Recording1">
		<detail>
			Recording1
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:35.030"
			timeRelativeToTestModuleStartTime="00:35.030"
			timeWallClock="18:15:56"
			time="00:35.030"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
